apiVersion: apps/v1
kind: Deployment
metadata:
  name: user01-order-test
  labels:
    app: user01-order-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user01-order-test
  template:
    metadata:
      labels:
        app: user01-order-test
    spec:
      containers:
        - name: user01-order-test
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user01-order-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
